name: product db built

on: push

jobs:
  build:

      runs.on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 14
          uses: actions/setup-java@v1
          with:
            java-versionen: 14
        - name: Build with Maven
          run: mvn -B package --file pom.xml